server:
  port: 8080
  
spring:
  profiles:
    active:
    - dev
      
---      
      
spring:
  main:
    banner-mode: off
  profiles: dev
  datasource:
   initialization-mode: never 
   hikari:
    maximum-pool-size: 5
    connection-timeout: 20000
   url: jdbc:postgresql://localhost:5432/@db.name@
   username: @db.user@
   password: @db.password@
   platform: @db.platform@
   driverClassName: @db.driverClassName@
  jpa:
    database: @jpa.database@
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
       format_sql: false
  flyway:
    user: @db.user@
    password: @db.password@
    url: jdbc:postgresql://localhost:5432/db.name@
    locations: classpath:db/migration
    enabled: true
  jackson:
      date-format: yyyy-MM-dd HH:mm:ss
      default-property-inclusion: NON_NULL
      locale: pt-BR
      time-zone: America/Sao_Paulo  

# Logs    
debug: true
trace: true
logging:
   level:
    com.logistic.resources.imp: DEBUG #WARN
    com.logistic.services.imp: DEBUG #WARN
    org.hibernate: DEBUG #WARN
# Server config      
server:
   compression:
      enabled: true
      min-response-size: 1
   port: ${SERVER_PORT:@port@}
   undertow:
      accesslog:
         dir: logs
         enabled: false
         pattern: '%t %a "%r" %s (%D ms)'    
    
# Actuators
management:
 endpoint:
  health:
   show-details: always
   group:
    custom:
     include: diskSpace,ping
     show-components: always #when_authorized //autenticado
     show-details: always #when_authorized //autenticado
 endpoints:     
  web:
   exposure:
    include: '*'  #health, info //configurar a exposição do health e info somente (example)
info:
  app:
    name: "@project.name@ - @project.version@" # Exibe nome e versão de projeto no actuator

# Configuração Spring Doc e swagger-ui
springdoc:
 api-docs:
  path: /api-docs
 swagger-ui:
  operationsSorter: method
  
---      
      
spring:
  main:
    banner-mode: console
  profiles: prod
 