#Escolher a porta
server:
  port: 8080
  
#Essa configuração deve ficar no teste
spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
   url: jdbc:h2:mem:testdb
   username: sa
   password: 
   driver-class-name: org.h2.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
       format_sql: true

# Actuators
management:
 endpoint:
  health:
   show-details: always
   group:
    custom:
     include: diskSpace,ping
     show-components: always #when_authorized //autenticado
     show-details: always #when_authorized //autenticado
 endpoints:     
  web:
   exposure:
    include: '*'  #health, info //configurar a exposição do health e info somente (example)
info:
  app:
    name: "@project.name@ - @project.version@" # Exibe nome e versão de projeto no actuator

# Configuração Spring Doc e swagger-ui
springdoc:
 api-docs:
  path: /api-docs
 swagger-ui:
  operationsSorter: method
